name: Host tests

on: [push]

jobs:
  build:
  
    runs-on: ubuntu-latest
     
    steps:
      - uses: actions/checkout@v1
       
      #Run perl5 script to verify file sizies in controls_xxx.txt files      
      #Compile
      - name: compile and run all host tests
        run:
          make host-test-all  

